language: node_js
node_js:
    - '8'
cache:
  apt: true
  directories:
  - node_modules
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
  ssh_known_hosts: github.com
env:
- CXX=g++-4.8
before_install:
  - git config --global user.name "zacksleo"
  - git config --global user.email "zacksleo@gmail.com"
  - git config --global push.default simple
script:
  - git clone -b master --single-branch https://${GH_TOKEN}@github.com/zacksleo/zacksleo.github.io.git --depth 1 .deploy_git -v
  - git remote add -f docs https://${GH_TOKEN}@github.com/zacksleo/zacksleo.github.io.git
  - git fetch docs
  - git subtree add --prefix=source/_posts docs docs --squash
  - npm install --no-optional
  - curl https://codeload.github.com/viosey/hexo-theme-material/tar.gz/1.5.0 -o themes/material.tar.gz && tar zxvf themes/material.tar.gz -C themes/
  - mv themes/hexo-theme-material-* themes/material &&  mv themes/_config.yml themes/material/_config.yml
after_script:
  - hexo generate
  - cp -r public/* .deploy_git/
  - cd .deploy_git
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force
branches:
  only:
    - hexo
